// ============================================================
// itemDatabase.js — Complete item definitions
// ============================================================
// Categories: consumable, weapon, armor, skill, material
// All items have: id, name, category, rarity, description,
// value (buy/sell), stackable, maxStack, effects.
// ============================================================

/**
 * Item rarities and their color codes.
 */
export const RARITY = {
  common: { name: 'Common', color: '#aaaaaa', mult: 1.0 },
  uncommon: { name: 'Uncommon', color: '#44cc44', mult: 1.5 },
  rare: { name: 'Rare', color: '#4488ff', mult: 2.5 },
  epic: { name: 'Epic', color: '#aa44ff', mult: 5.0 },
  legendary: { name: 'Legendary', color: '#ffaa00', mult: 10.0 },
};

/**
 * @typedef {object} ItemDef
 * @property {string} id
 * @property {string} name
 * @property {string} category    - consumable | weapon | armor | skill | material
 * @property {string} rarity      - common | uncommon | rare | epic | legendary
 * @property {string} description
 * @property {number} buyPrice
 * @property {number} sellPrice
 * @property {boolean} stackable
 * @property {number} maxStack
 * @property {object} [effects]   - Category-specific effects
 */

export const ITEMS = {
  // ═══════════════════════════════════════════════════════════
  // CONSUMABLES
  // ═══════════════════════════════════════════════════════════
  healthPotionSmall: {
    id: 'healthPotionSmall',
    name: 'Small Health Potion',
    category: 'consumable',
    rarity: 'common',
    description: 'Restores 30 HP instantly.',
    buyPrice: 50,
    sellPrice: 15,
    stackable: true,
    maxStack: 99,
    effects: { type: 'heal', amount: 30, cooldown: 3 },
  },
  healthPotionMedium: {
    id: 'healthPotionMedium',
    name: 'Medium Health Potion',
    category: 'consumable',
    rarity: 'uncommon',
    description: 'Restores 80 HP instantly.',
    buyPrice: 150,
    sellPrice: 50,
    stackable: true,
    maxStack: 50,
    effects: { type: 'heal', amount: 80, cooldown: 5 },
  },
  healthPotionLarge: {
    id: 'healthPotionLarge',
    name: 'Large Health Potion',
    category: 'consumable',
    rarity: 'rare',
    description: 'Restores 200 HP instantly.',
    buyPrice: 500,
    sellPrice: 175,
    stackable: true,
    maxStack: 30,
    effects: { type: 'heal', amount: 200, cooldown: 8 },
  },
  staminaPotionSmall: {
    id: 'staminaPotionSmall',
    name: 'Small Stamina Potion',
    category: 'consumable',
    rarity: 'common',
    description: 'Restores 25 Stamina instantly.',
    buyPrice: 40,
    sellPrice: 12,
    stackable: true,
    maxStack: 99,
    effects: { type: 'stamina', amount: 25, cooldown: 3 },
  },
  staminaPotionMedium: {
    id: 'staminaPotionMedium',
    name: 'Medium Stamina Potion',
    category: 'consumable',
    rarity: 'uncommon',
    description: 'Restores 60 Stamina instantly.',
    buyPrice: 120,
    sellPrice: 40,
    stackable: true,
    maxStack: 50,
    effects: { type: 'stamina', amount: 60, cooldown: 5 },
  },
  antidote: {
    id: 'antidote',
    name: 'Antidote',
    category: 'consumable',
    rarity: 'common',
    description: 'Cures poison status.',
    buyPrice: 60,
    sellPrice: 20,
    stackable: true,
    maxStack: 30,
    effects: { type: 'cure', status: 'poison', cooldown: 2 },
  },
  strengthElixir: {
    id: 'strengthElixir',
    name: 'Strength Elixir',
    category: 'consumable',
    rarity: 'rare',
    description: 'Increases damage by 30% for 60 seconds.',
    buyPrice: 400,
    sellPrice: 130,
    stackable: true,
    maxStack: 10,
    effects: { type: 'buff', stat: 'damage', mult: 1.3, duration: 60, cooldown: 10 },
  },
  speedPotion: {
    id: 'speedPotion',
    name: 'Speed Potion',
    category: 'consumable',
    rarity: 'uncommon',
    description: 'Increases movement speed by 40% for 30 seconds.',
    buyPrice: 200,
    sellPrice: 65,
    stackable: true,
    maxStack: 20,
    effects: { type: 'buff', stat: 'speed', mult: 1.4, duration: 30, cooldown: 8 },
  },

  // ═══════════════════════════════════════════════════════════
  // WEAPONS
  // ═══════════════════════════════════════════════════════════
  woodenSword: {
    id: 'woodenSword',
    name: 'Wooden Sword',
    category: 'weapon',
    rarity: 'common',
    description: 'A basic training sword.',
    buyPrice: 100,
    sellPrice: 25,
    stackable: false,
    maxStack: 1,
    effects: { slot: 'weapon', damage: 5, attackSpeed: 0, critChance: 0.02 },
  },
  ironSword: {
    id: 'ironSword',
    name: 'Iron Sword',
    category: 'weapon',
    rarity: 'common',
    description: 'A sturdy iron blade.',
    buyPrice: 300,
    sellPrice: 90,
    stackable: false,
    maxStack: 1,
    effects: { slot: 'weapon', damage: 12, attackSpeed: 0, critChance: 0.05 },
  },
  steelGreatsword: {
    id: 'steelGreatsword',
    name: 'Steel Greatsword',
    category: 'weapon',
    rarity: 'uncommon',
    description: 'A heavy two-handed sword. Slow but powerful.',
    buyPrice: 800,
    sellPrice: 260,
    stackable: false,
    maxStack: 1,
    effects: { slot: 'weapon', damage: 28, attackSpeed: -0.15, critChance: 0.08 },
  },
  cursedBlade: {
    id: 'cursedBlade',
    name: 'Cursed Blade',
    category: 'weapon',
    rarity: 'epic',
    description: 'A blade imbued with dark energy. Drains life on hit.',
    buyPrice: 5000,
    sellPrice: 1500,
    stackable: false,
    maxStack: 1,
    effects: { slot: 'weapon', damage: 45, attackSpeed: 0.05, critChance: 0.12, lifesteal: 0.08 },
  },
  heavyAxe: {
    id: 'heavyAxe',
    name: 'Heavy Axe',
    category: 'weapon',
    rarity: 'uncommon',
    description: 'A lumberjack\'s tool repurposed for battle.',
    buyPrice: 600,
    sellPrice: 200,
    stackable: false,
    maxStack: 1,
    effects: { slot: 'weapon', damage: 22, attackSpeed: -0.1, critChance: 0.06 },
  },
  knightSword: {
    id: 'knightSword',
    name: 'Knight\'s Longsword',
    category: 'weapon',
    rarity: 'rare',
    description: 'A well-balanced blade of a fallen knight.',
    buyPrice: 2000,
    sellPrice: 650,
    stackable: false,
    maxStack: 1,
    effects: { slot: 'weapon', damage: 35, attackSpeed: 0.05, critChance: 0.1 },
  },
  shortBow: {
    id: 'shortBow',
    name: 'Short Bow',
    category: 'weapon',
    rarity: 'common',
    description: 'A simple wooden bow.',
    buyPrice: 250,
    sellPrice: 75,
    stackable: false,
    maxStack: 1,
    effects: { slot: 'weapon', damage: 10, attackSpeed: 0.1, critChance: 0.05, ranged: true },
  },
  rustyDagger: {
    id: 'rustyDagger',
    name: 'Rusty Dagger',
    category: 'weapon',
    rarity: 'common',
    description: 'A goblin\'s rusty blade. Fast but weak.',
    buyPrice: 50,
    sellPrice: 12,
    stackable: false,
    maxStack: 1,
    effects: { slot: 'weapon', damage: 3, attackSpeed: 0.2, critChance: 0.08 },
  },

  // ═══════════════════════════════════════════════════════════
  // ARMOR
  // ═══════════════════════════════════════════════════════════
  clothArmor: {
    id: 'clothArmor',
    name: 'Cloth Armor',
    category: 'armor',
    rarity: 'common',
    description: 'Basic cloth garments.',
    buyPrice: 80,
    sellPrice: 20,
    stackable: false,
    maxStack: 1,
    effects: { slot: 'chest', defence: 3, hp: 0 },
  },
  leatherArmor: {
    id: 'leatherArmor',
    name: 'Leather Armor',
    category: 'armor',
    rarity: 'common',
    description: 'Tough leather vest.',
    buyPrice: 250,
    sellPrice: 75,
    stackable: false,
    maxStack: 1,
    effects: { slot: 'chest', defence: 8, hp: 10 },
  },
  chainMail: {
    id: 'chainMail',
    name: 'Chain Mail',
    category: 'armor',
    rarity: 'uncommon',
    description: 'Interlocking metal rings for solid protection.',
    buyPrice: 700,
    sellPrice: 230,
    stackable: false,
    maxStack: 1,
    effects: { slot: 'chest', defence: 18, hp: 25 },
  },
  plateArmor: {
    id: 'plateArmor',
    name: 'Plate Armor',
    category: 'armor',
    rarity: 'rare',
    description: 'Full plate armor. Heavy but very protective.',
    buyPrice: 2500,
    sellPrice: 800,
    stackable: false,
    maxStack: 1,
    effects: { slot: 'chest', defence: 35, hp: 50, speedPenalty: -0.1 },
  },
  demonArmor: {
    id: 'demonArmor',
    name: 'Demon Armor',
    category: 'armor',
    rarity: 'legendary',
    description: 'Forged from demon bones. Grants immense defense and lifesteal.',
    buyPrice: 15000,
    sellPrice: 5000,
    stackable: false,
    maxStack: 1,
    effects: { slot: 'chest', defence: 60, hp: 100, lifesteal: 0.05 },
  },
  ironHelmet: {
    id: 'ironHelmet',
    name: 'Iron Helmet',
    category: 'armor',
    rarity: 'common',
    description: 'Basic head protection.',
    buyPrice: 150,
    sellPrice: 45,
    stackable: false,
    maxStack: 1,
    effects: { slot: 'head', defence: 5, hp: 5 },
  },
  leatherBoots: {
    id: 'leatherBoots',
    name: 'Leather Boots',
    category: 'armor',
    rarity: 'common',
    description: 'Comfortable leather boots.',
    buyPrice: 120,
    sellPrice: 35,
    stackable: false,
    maxStack: 1,
    effects: { slot: 'feet', defence: 3, speedBonus: 0.05 },
  },

  // ═══════════════════════════════════════════════════════════
  // MATERIALS (drops from creatures)
  // ═══════════════════════════════════════════════════════════
  slimeGel: {
    id: 'slimeGel',
    name: 'Slime Gel',
    category: 'material',
    rarity: 'common',
    description: 'Sticky gel from a slime.',
    buyPrice: 5,
    sellPrice: 2,
    stackable: true,
    maxStack: 999,
    effects: {},
  },
  slimeCore: {
    id: 'slimeCore',
    name: 'Slime Core',
    category: 'material',
    rarity: 'uncommon',
    description: 'The crystallized core of a slime.',
    buyPrice: 20,
    sellPrice: 8,
    stackable: true,
    maxStack: 999,
    effects: {},
  },
  goblinEar: {
    id: 'goblinEar',
    name: 'Goblin Ear',
    category: 'material',
    rarity: 'common',
    description: 'Proof of a goblin kill.',
    buyPrice: 8,
    sellPrice: 3,
    stackable: true,
    maxStack: 999,
    effects: {},
  },
  wolfPelt: {
    id: 'wolfPelt',
    name: 'Wolf Pelt',
    category: 'material',
    rarity: 'common',
    description: 'A thick wolf hide.',
    buyPrice: 15,
    sellPrice: 5,
    stackable: true,
    maxStack: 999,
    effects: {},
  },
  fang: {
    id: 'fang',
    name: 'Sharp Fang',
    category: 'material',
    rarity: 'uncommon',
    description: 'A razor-sharp fang.',
    buyPrice: 25,
    sellPrice: 10,
    stackable: true,
    maxStack: 999,
    effects: {},
  },
  mossStone: {
    id: 'mossStone',
    name: 'Moss Stone',
    category: 'material',
    rarity: 'uncommon',
    description: 'A moss-covered stone with magical properties.',
    buyPrice: 30,
    sellPrice: 12,
    stackable: true,
    maxStack: 999,
    effects: {},
  },
  ancientBark: {
    id: 'ancientBark',
    name: 'Ancient Bark',
    category: 'material',
    rarity: 'rare',
    description: 'Bark from a centuries-old tree golem.',
    buyPrice: 80,
    sellPrice: 30,
    stackable: true,
    maxStack: 999,
    effects: {},
  },
  natureShard: {
    id: 'natureShard',
    name: 'Nature Shard',
    category: 'material',
    rarity: 'rare',
    description: 'A crystal imbued with natural energy.',
    buyPrice: 100,
    sellPrice: 40,
    stackable: true,
    maxStack: 999,
    effects: {},
  },
  orcTusk: {
    id: 'orcTusk',
    name: 'Orc Tusk',
    category: 'material',
    rarity: 'uncommon',
    description: 'A broken orc tusk.',
    buyPrice: 35,
    sellPrice: 14,
    stackable: true,
    maxStack: 999,
    effects: {},
  },
  cursedBone: {
    id: 'cursedBone',
    name: 'Cursed Bone',
    category: 'material',
    rarity: 'rare',
    description: 'Bones radiating dark energy.',
    buyPrice: 90,
    sellPrice: 35,
    stackable: true,
    maxStack: 999,
    effects: {},
  },
  dragonScale: {
    id: 'dragonScale',
    name: 'Dragon Scale',
    category: 'material',
    rarity: 'epic',
    description: 'An incredibly hard scale from a dragon.',
    buyPrice: 500,
    sellPrice: 200,
    stackable: true,
    maxStack: 99,
    effects: {},
  },
  fireEssence: {
    id: 'fireEssence',
    name: 'Fire Essence',
    category: 'material',
    rarity: 'rare',
    description: 'Concentrated fire energy.',
    buyPrice: 120,
    sellPrice: 50,
    stackable: true,
    maxStack: 99,
    effects: {},
  },
  frostCrystal: {
    id: 'frostCrystal',
    name: 'Frost Crystal',
    category: 'material',
    rarity: 'rare',
    description: 'A crystal of eternal ice.',
    buyPrice: 110,
    sellPrice: 45,
    stackable: true,
    maxStack: 99,
    effects: {},
  },
  iceCore: {
    id: 'iceCore',
    name: 'Ice Core',
    category: 'material',
    rarity: 'epic',
    description: 'The frozen heart of an ice elemental.',
    buyPrice: 400,
    sellPrice: 160,
    stackable: true,
    maxStack: 50,
    effects: {},
  },
  dragonHeart: {
    id: 'dragonHeart',
    name: 'Dragon Heart',
    category: 'material',
    rarity: 'legendary',
    description: 'The still-beating heart of a fallen dragon.',
    buyPrice: 2000,
    sellPrice: 800,
    stackable: true,
    maxStack: 10,
    effects: {},
  },
  demonHeart: {
    id: 'demonHeart',
    name: 'Demon Heart',
    category: 'material',
    rarity: 'legendary',
    description: 'Pulsing with dark power.',
    buyPrice: 3000,
    sellPrice: 1200,
    stackable: true,
    maxStack: 10,
    effects: {},
  },
  legendaryGem: {
    id: 'legendaryGem',
    name: 'Legendary Gem',
    category: 'material',
    rarity: 'legendary',
    description: 'A gem of unimaginable power.',
    buyPrice: 5000,
    sellPrice: 2000,
    stackable: true,
    maxStack: 5,
    effects: {},
  },
  ancientShard: {
    id: 'ancientShard',
    name: 'Ancient Shard',
    category: 'material',
    rarity: 'epic',
    description: 'A fragment of an ancient artifact.',
    buyPrice: 600,
    sellPrice: 250,
    stackable: true,
    maxStack: 50,
    effects: {},
  },
  ancientRune: {
    id: 'ancientRune',
    name: 'Ancient Rune',
    category: 'material',
    rarity: 'epic',
    description: 'Inscribed with forgotten magic.',
    buyPrice: 800,
    sellPrice: 320,
    stackable: true,
    maxStack: 30,
    effects: {},
  },
  sunStone: {
    id: 'sunStone',
    name: 'Sun Stone',
    category: 'material',
    rarity: 'legendary',
    description: 'Radiates warmth and light energy.',
    buyPrice: 4000,
    sellPrice: 1600,
    stackable: true,
    maxStack: 10,
    effects: {},
  },
  goldOre: {
    id: 'goldOre',
    name: 'Gold Ore',
    category: 'material',
    rarity: 'uncommon',
    description: 'Raw gold ore. Valuable.',
    buyPrice: 50,
    sellPrice: 25,
    stackable: true,
    maxStack: 999,
    effects: {},
  },
  herb: {
    id: 'herb',
    name: 'Herb',
    category: 'material',
    rarity: 'common',
    description: 'A common medicinal herb.',
    buyPrice: 5,
    sellPrice: 1,
    stackable: true,
    maxStack: 999,
    effects: {},
  },
  wood: {
    id: 'wood',
    name: 'Wood',
    category: 'material',
    rarity: 'common',
    description: 'Common lumber.',
    buyPrice: 3,
    sellPrice: 1,
    stackable: true,
    maxStack: 999,
    effects: {},
  },
  stone: {
    id: 'stone',
    name: 'Stone',
    category: 'material',
    rarity: 'common',
    description: 'A chunk of stone.',
    buyPrice: 3,
    sellPrice: 1,
    stackable: true,
    maxStack: 999,
    effects: {},
  },
  arrow: {
    id: 'arrow',
    name: 'Arrow',
    category: 'material',
    rarity: 'common',
    description: 'Standard arrow.',
    buyPrice: 2,
    sellPrice: 1,
    stackable: true,
    maxStack: 999,
    effects: {},
  },
  wolfMeat: {
    id: 'wolfMeat',
    name: 'Wolf Meat',
    category: 'material',
    rarity: 'common',
    description: 'Raw edible meat.',
    buyPrice: 8,
    sellPrice: 3,
    stackable: true,
    maxStack: 999,
    effects: {},
  },
  mushroom: {
    id: 'mushroom',
    name: 'Mushroom',
    category: 'material',
    rarity: 'common',
    description: 'A forest mushroom.',
    buyPrice: 4,
    sellPrice: 1,
    stackable: true,
    maxStack: 999,
    effects: {},
  },
  darkWood: {
    id: 'darkWood',
    name: 'Dark Wood',
    category: 'material',
    rarity: 'uncommon',
    description: 'Dense dark wood from the goblin forest.',
    buyPrice: 15,
    sellPrice: 6,
    stackable: true,
    maxStack: 999,
    effects: {},
  },
};

/**
 * Get item definition by ID.
 */
export function getItem(id) {
  return ITEMS[id] || null;
}

/**
 * Get all items of a category.
 */
export function getItemsByCategory(category) {
  return Object.values(ITEMS).filter(i => i.category === category);
}

/**
 * Get all items of a rarity.
 */
export function getItemsByRarity(rarity) {
  return Object.values(ITEMS).filter(i => i.rarity === rarity);
}

/**
 * Get shop inventory for a zone.
 */
export function getShopInventory(zoneId) {
  const base = ['healthPotionSmall', 'staminaPotionSmall', 'antidote', 'clothArmor', 'woodenSword'];
  const zoneItems = {
    rookieTown: [...base, 'ironSword', 'leatherArmor', 'ironHelmet', 'leatherBoots'],
    goblinForest: [...base, 'steelGreatsword', 'chainMail', 'healthPotionMedium', 'staminaPotionMedium', 'speedPotion'],
    dragonValley: [...base, 'healthPotionMedium', 'healthPotionLarge', 'strengthElixir', 'knightSword', 'plateArmor'],
    frozenNorth: [...base, 'healthPotionLarge', 'strengthElixir', 'speedPotion'],
    desertEmpire: [...base, 'healthPotionLarge', 'strengthElixir', 'speedPotion', 'staminaPotionMedium'],
  };
  return (zoneItems[zoneId] || base).map(id => ITEMS[id]).filter(Boolean);
}
